// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIA3rUxODMyQNywINK7fDEcylrp3dX9VE',
    appId: '1:405479987783:web:32b90c3b8457305f0aef62',
    messagingSenderId: '405479987783',
    projectId: 'casa-grand-adv',
    authDomain: 'casa-grand-adv.firebaseapp.com',
    storageBucket: 'casa-grand-adv.appspot.com',
    measurementId: 'G-48VB6Y4SWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzs2_pfZ5vxzbApQnE96dDC0iOc1G7ab0',
    appId: '1:405479987783:android:ce9071e5c42dbc9b0aef62',
    messagingSenderId: '405479987783',
    projectId: 'casa-grand-adv',
    storageBucket: 'casa-grand-adv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWtRb8HE36aw75lsHAjPD7nKY_oYB0QcE',
    appId: '1:405479987783:ios:e5249a21962801e20aef62',
    messagingSenderId: '405479987783',
    projectId: 'casa-grand-adv',
    storageBucket: 'casa-grand-adv.appspot.com',
    iosClientId: '405479987783-kkcadn6kapcp6l9c8v0rams1b02d5gt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.casaGrandeAdv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWtRb8HE36aw75lsHAjPD7nKY_oYB0QcE',
    appId: '1:405479987783:ios:e5249a21962801e20aef62',
    messagingSenderId: '405479987783',
    projectId: 'casa-grand-adv',
    storageBucket: 'casa-grand-adv.appspot.com',
    iosClientId: '405479987783-kkcadn6kapcp6l9c8v0rams1b02d5gt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.casaGrandeAdv',
  );
}
